version: '3'

services:
  db:
   container_name: postgres_buffalo
   image: postgres:9.4
   #restart: always
   tty: true
   volumes:
     - .pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=example_development
   ports:
    - "5432:5432"